name: Build and Dependency Graph

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install


      # Upload Maven Dependency Snapshot using GitHub's official action
      - name: Upload Maven Dependency Snapshot
        uses: github/dependency-submission-action@v1  # Official GitHub action for submitting dependency snapshot
        with:
          repository: ${{ github.repository }}  # Automatically submits dependency data to GitHub